# Generated by Django 3.1.7 on 2021-05-15 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_danhmucgiong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tb_nhacungcap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
                ('diachi', models.CharField(max_length=255, null=True)),
                ('sdt', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tb_noilamviec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
                ('trangthai', models.CharField(max_length=255)),
                ('hinh', models.ImageField(upload_to='images/noilamviec')),
            ],
        ),
        migrations.CreateModel(
            name='tb_thuoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
                ('soluong', models.CharField(max_length=255)),
                ('gia', models.CharField(max_length=255)),
                ('nhacungcap', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nong_san.tb_nhacungcap')),
            ],
        ),
        migrations.CreateModel(
            name='tb_taikhoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoten', models.CharField(max_length=255)),
                ('diachi', models.CharField(max_length=255)),
                ('sdt', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tb_phanbon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
                ('soluong', models.CharField(max_length=255)),
                ('hinh', models.ImageField(upload_to='images/phanbon')),
                ('nhacungcap', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nong_san.tb_nhacungcap')),
            ],
        ),
        migrations.CreateModel(
            name='tb_giong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
                ('gia', models.CharField(max_length=255)),
                ('thoigiansinhtruong', models.CharField(max_length=255)),
                ('hinh', models.ImageField(upload_to='images/giong')),
                ('hinhthai', models.CharField(max_length=255)),
                ('soluong', models.CharField(max_length=255)),
                ('danhmucgiong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nong_san.tb_danhmucgiong')),
                ('nhacungcap', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nong_san.tb_nhacungcap')),
            ],
        ),
        migrations.CreateModel(
            name='tb_congviec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
                ('trangthai', models.CharField(max_length=255)),
                ('thoigian', models.DateField(null=True)),
                ('giong', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nong_san.tb_giong')),
                ('noilamviec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nong_san.tb_noilamviec')),
                ('phanbon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nong_san.tb_phanbon')),
                ('thuoc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nong_san.tb_thuoc')),
            ],
        ),
        migrations.CreateModel(
            name='tb_congnhan_congviec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congnhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nong_san.tb_taikhoan')),
                ('congviec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nong_san.tb_congviec')),
            ],
        ),
        migrations.CreateModel(
            name='tb_baocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trangthai', models.CharField(max_length=255)),
                ('mota', models.CharField(max_length=255)),
                ('hinh', models.ImageField(upload_to='images/baocao')),
                ('congnhan_congviec', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nong_san.tb_congnhan_congviec')),
            ],
        ),
    ]
