# Generated by Django 3.1.7 on 2021-05-15 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nong_san', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tb_danhmucgiong',
            table='danhmucgiong',
        ),
    ]
