# Generated by Django 3.1.7 on 2021-05-15 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nong_san', '0002_auto_20210515_1255'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tb_baocao',
            table='baocao',
        ),
        migrations.AlterModelTable(
            name='tb_congnhan_congviec',
            table='congnhan_congviec',
        ),
        migrations.AlterModelTable(
            name='tb_congviec',
            table='congviec',
        ),
        migrations.AlterModelTable(
            name='tb_giong',
            table='giong',
        ),
        migrations.AlterModelTable(
            name='tb_nhacungcap',
            table='nhacungcap',
        ),
        migrations.AlterModelTable(
            name='tb_noilamviec',
            table='noilamviec',
        ),
        migrations.AlterModelTable(
            name='tb_phanbon',
            table='phanbon',
        ),
        migrations.AlterModelTable(
            name='tb_taikhoan',
            table='taikhoan',
        ),
        migrations.AlterModelTable(
            name='tb_thuoc',
            table='thuoc',
        ),
    ]
