# Generated by Django 3.1.7 on 2021-05-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nong_san', '0003_auto_20210515_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_baocao',
            name='hinh',
            field=models.CharField(max_length=255),
        ),
    ]
