# Generated by Django 3.2.1 on 2021-05-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210506_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(default='', upload_to='images/categories'),
        ),
    ]
