# Generated by Django 3.2.1 on 2021-05-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='evaluation',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(max_length=1000),
        ),
    ]
