# Generated by Django 3.2.1 on 2021-05-09 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_comments_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('qty', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=100, null=True)),
                ('create_date', models.DateField(default=datetime.date(2021, 5, 9))),
                ('end_date', models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='voucher_code',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
