# Generated by Django 3.2.1 on 2021-05-13 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_voucher_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='create_date',
            field=models.DateField(default=datetime.date(2021, 5, 13)),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='create_date',
            field=models.DateField(default=datetime.date(2021, 5, 13)),
        ),
    ]
